[package]
authors = ["Aaron Trent <novacrazy@gmail.com>"]
description = "Dual Number Implementation combined from multiple other implementations"
license = "MIT"
name = "dual_num"
version = "0.1.0"
include = ["src/**/*", "Cargo.toml"]
keywords = ["dual", "number"]
readme = "README.md"
repository = "https://github.com/novacrazy/dual_num"

[dependencies]
num-traits = "0.1.37"